// <auto-generated />
using System;
using DotNetCoreWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCoreWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCoreWebApp.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JobCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MinimumQualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobCode = "JOB111",
                            LastApplyDate = new DateTime(2023, 1, 22, 21, 32, 11, 680, DateTimeKind.Local).AddTicks(1661),
                            MinimumQualification = "BCA",
                            SortDescription = "Software Engineer",
                            Title = "DOT NET",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            JobCode = "JOB112",
                            LastApplyDate = new DateTime(2023, 1, 22, 21, 32, 11, 684, DateTimeKind.Local).AddTicks(6739),
                            MinimumQualification = "BCA",
                            SortDescription = "Software Engineer",
                            Title = "PHP",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            JobCode = "JOB113",
                            LastApplyDate = new DateTime(2023, 1, 22, 21, 32, 11, 684, DateTimeKind.Local).AddTicks(6916),
                            MinimumQualification = "BCA",
                            SortDescription = "Software Engineer",
                            Title = "Tech Lead",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DotNetCoreWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "shivamchouhan544@gmail.com",
                            Name = "Shivam Chouhan",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "navinkumar@gmail.com",
                            Name = "Navin Kumar",
                            Password = "1234567"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kiran@gmail.com",
                            Name = "Kiran Kher",
                            Password = "12345678"
                        });
                });

            modelBuilder.Entity("DotNetCoreWebApp.Models.Job", b =>
                {
                    b.HasOne("DotNetCoreWebApp.Models.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
